name: Example
on:
  push:
env:
  AWS_REGION : us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: sleep 1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::217212059928:role/ExampleGithubRole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - run: aws sts get-caller-identity

      - run: aws configure list
